name: deployment
 
on:
  push:
    branches: master
    
env:
  DEP_PATH: requirements.txt

jobs:
 
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: deployment
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: "chatbot-lyh"  # Rename this to the app of your Heroku app.
        run: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
